# Generated by Django 5.2 on 2025-04-25 16:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='room',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='room',
            name='players',
        ),
        migrations.AlterField(
            model_name='room',
            name='topic',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='debate.topic'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_in_room', to='rooms.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(related_name='rooms', to='rooms.player'),
        ),
    ]
