# Generated by Django 5.2 on 2025-04-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_created_at_remove_room_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='content_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='poi_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='strategy_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='style_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_score',
            field=models.FloatField(default=0),
        ),
    ]
