# Generated by Django 5.2 on 2025-04-27 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_player_content_score_player_notes_player_poi_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name_plural': 'Tutorial Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF Document'), ('article', 'Web Article'), ('video', 'Video Tutorial'), ('guide', 'Guide')], max_length=20)),
                ('icon_class', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='tutorials/files/')),
                ('url', models.URLField(blank=True, null=True)),
                ('external_link', models.URLField(blank=True, null=True)),
                ('length', models.CharField(blank=True, help_text="E.g., '15 pages', '8 min read'", max_length=50)),
                ('duration', models.CharField(blank=True, help_text='Video duration in format MM:SS', max_length=10)),
                ('video_embed_url', models.URLField(blank=True, help_text='YouTube/Vimeo embed URL', null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='rooms.tutorialcategory')),
            ],
            options={
                'ordering': ['category', 'order', '-created_at'],
            },
        ),
    ]
