# Generated by Django 5.2 on 2025-04-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_tutorialcategory_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='doc_image',
            field=models.ImageField(blank=True, default='defaults/default_image.jpg', null=True, upload_to='doc_images/'),
        ),
    ]
